{{- if .Values.mta.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: rspamd-mta-config
  namespace: {{ .Release.Namespace }}
data:
  actions.conf: |
    reject = {{ .Values.mta.rspamd.rejectScore }};
    add_header = {{ .Values.mta.rspamd.addHeaderScore }};
  dkim_signing.conf: |
    enabled = true;
    use_domain = "header";
    selector = {{ .Values.dkim.selector | quote }};
    path = "/etc/rspamd/dkim/$domain.$selector.key";
  rbl.conf: |
    enabled = false;
  worker-proxy.inc: |
    milter = yes;
    timeout = 120s;
    upstream "local" {
      default = yes;
      self_scan = yes;
    }
{{- end }}
