{{- if or .Values.mx.enabled .Values.mta.enabled .Values.fwd.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: relay-rspamd-config
  namespace: {{ .Release.Namespace }}
data:
  actions.conf: |
    reject = {{ .Values.rspamd.rejectScore }};
    add_header = {{ .Values.rspamd.addHeaderScore }};
    greylist = null;
  dkim_signing.conf: |
    enabled = false;
  rbl.conf: |
    enabled = false;
  antivirus.conf: |
    enabled = false;
  neural.conf: |
    enabled = false;
  fuzzy_check.conf: |
    enabled = false;
  url_redirector.conf: |
    enabled = false;
  replies.conf: |
    enabled = false;
  greylist.conf: |
    enabled = false;
  classifier-bayes.conf: |
    enabled = false;
  worker-normal.inc: |
    count = 1;
  worker-proxy.inc: |
    milter = yes;
    timeout = 120s;
    upstream "local" {
      default = yes;
      self_scan = yes;
    }
{{- end }}
