{{- if .Values.mx.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: rspamd-mx-config
  namespace: {{ .Release.Namespace }}
data:
  actions.conf: |
    reject = {{ .Values.mx.rspamd.rejectScore }};
    add_header = {{ .Values.mx.rspamd.addHeaderScore }};
    greylist = 4;
  milter_headers.conf: |
    use = ["x-spamd-bar", "x-spam-level", "x-spam-status", "authentication-results"];
    authenticated_headers = ["authentication-results"];
  worker-proxy.inc: |
    milter = yes;
    timeout = 120s;
    upstream "local" {
      default = yes;
      self_scan = yes;
    }
{{- end }}
