{{- if .Values.mta.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: relay-rspamd-mta
  namespace: {{ .Release.Namespace }}
  labels:
    app: relay-rspamd-mta
spec:
  replicas: 1
  selector:
    matchLabels:
      app: relay-rspamd-mta
  template:
    metadata:
      labels:
        app: relay-rspamd-mta
    spec:
      containers:
        - name: rspamd
          image: "{{ .Values.image.rspamd.repository }}:{{ .Values.image.rspamd.tag }}"
          imagePullPolicy: {{ .Values.image.rspamd.pullPolicy }}
          ports:
            - containerPort: 11332
              name: milter
            - containerPort: 11334
              name: web
          volumeMounts:
            - name: config
              mountPath: /etc/rspamd/local.d
              readOnly: true
            {{- include "yarilo-postfix.dkimMount" .Values.dkim.secretName | nindent 12 }}
          resources:
            {{- toYaml .Values.resources.rspamd | nindent 12 }}
      volumes:
        - name: config
          configMap:
            name: rspamd-mta-config
        {{- include "yarilo-postfix.dkimVolume" .Values.dkim.secretName | nindent 8 }}
{{- end }}
