{{- if .Values.opendkim.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: relay-opendkim
  namespace: {{ .Release.Namespace }}
  labels:
    app: relay-opendkim
spec:
  replicas: 1
  selector:
    matchLabels:
      app: relay-opendkim
  template:
    metadata:
      labels:
        app: relay-opendkim
    spec:
      containers:
        - name: opendkim
          image: "{{ .Values.image.opendkim.repository }}:{{ .Values.image.opendkim.tag }}"
          imagePullPolicy: {{ .Values.image.opendkim.pullPolicy }}
          ports:
            - containerPort: 8891
              name: milter
          command: ["/bin/sh", "-c"]
          args:
            - |
              sed \
                -e "s|\${MYSQL_USER}|${MYSQL_USER}|g" \
                -e "s|\${MYSQL_PASSWORD}|${MYSQL_PASSWORD}|g" \
                -e "s|\${MYSQL_HOST}|${MYSQL_HOST}|g" \
                -e "s|\${MYSQL_DBNAME}|${MYSQL_DBNAME}|g" \
                /etc/opendkim-tpl/opendkim.conf.tpl > /etc/opendkim/opendkim.conf
              syslogd -f /etc/opendkim-tpl/syslog.conf -n &
              exec opendkim -f -x /etc/opendkim/opendkim.conf
          env:
            {{- include "yarilo-postfix.mysqlEnv" .Values | nindent 12 }}
          volumeMounts:
            - name: opendkim-tpl
              mountPath: /etc/opendkim-tpl
              readOnly: true
            - name: opendkim-run
              mountPath: /etc/opendkim
          resources:
            {{- toYaml .Values.resources.opendkim | nindent 12 }}
      volumes:
        - name: opendkim-tpl
          configMap:
            name: relay-opendkim-config
        - name: opendkim-run
          emptyDir: {}
{{- end }}
