{{- if or .Values.mx.enabled .Values.mta.enabled .Values.fwd.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: relay-rspamd
  namespace: {{ .Release.Namespace }}
  labels:
    app: relay-rspamd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: relay-rspamd
  template:
    metadata:
      labels:
        app: relay-rspamd
    spec:
      containers:
        - name: rspamd
          image: "{{ .Values.image.rspamd.repository }}:{{ .Values.image.rspamd.tag }}"
          imagePullPolicy: {{ .Values.image.rspamd.pullPolicy }}
          ports:
            - containerPort: 11332
              name: milter
            - containerPort: 11333
              name: controller
          volumeMounts:
            - name: config
              mountPath: /etc/rspamd/local.d
          resources:
            {{- toYaml .Values.resources.rspamd | nindent 12 }}
      volumes:
        - name: config
          configMap:
            name: relay-rspamd-config
{{- end }}
