{{- if .Values.mx.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: relay-rspamd-mx
  namespace: {{ .Release.Namespace }}
  labels:
    app: relay-rspamd-mx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: relay-rspamd-mx
  template:
    metadata:
      labels:
        app: relay-rspamd-mx
    spec:
      containers:
        - name: rspamd
          image: "{{ .Values.image.rspamd.repository }}:{{ .Values.image.rspamd.tag }}"
          imagePullPolicy: {{ .Values.image.rspamd.pullPolicy }}
          ports:
            - containerPort: 11332
              name: milter
            - containerPort: 11334
              name: web
          volumeMounts:
            - name: config
              mountPath: /etc/rspamd/local.d
              readOnly: true
          resources:
            {{- toYaml .Values.resources.rspamd | nindent 12 }}
      volumes:
        - name: config
          configMap:
            name: rspamd-mx-config
{{- end }}
