{{- if .Values.postsrsd.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: relay-postsrsd
  namespace: {{ .Release.Namespace }}
  labels:
    app: relay-postsrsd
spec:
  type: {{ .Values.postsrsd.service.type }}
  selector:
    app: relay-postsrsd
  ports:
    - name: socketmap
      port: 10003
      targetPort: socketmap
{{- end }}
